In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import glob  # For handling file paths

In [4]:
news = pd.read_csv(r"C:\Users\HP\Downloads\week00_data\data.csv")

In [3]:
rating = pd.read_csv(r"C:\Users\HP\Downloads\week00_data\rating.csv")

In [5]:
traffic = pd.read_csv(r"C:\Users\HP\Downloads\week00_data\traffic.csv")

In [6]:
domain_location = pd.read_csv(r"C:\Users\HP\Downloads\week00_data\domains_location.csv")

In [5]:
traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   GlobalRank      1000000 non-null  int64
 1   TldRank         1000000 non-null  int64
 2   Domain          1000000 non-null  object
 3   TLD             1000000 non-null  object
 4   RefSubNets      1000000 non-null  int64
 5   RefIPs          1000000 non-null  int64
 6   IDN_Domain      1000000 non-null  object
 7   IDN_TLD         1000000 non-null  object
 8   PrevGlobalRank  1000000 non-null  int64
 9   PrevTldRank     1000000 non-null  int64
 10  PrevRefSubNets  1000000 non-null  int64
 11  PrevRefIPs      1000000 non-null  int64
dtypes: int64(8), object(4)
memory usage: 91.6+ MB

In [6]:
traffic.isnull().sum()

GlobalRank        0
TldRank           0
Domain            0
TLD               0
RefSubNets        0
RefIPs            0
IDN_Domain        0
IDN_TLD           0
PrevGlobalRank    0
PrevTldRank       0
PrevRefSubNets    0
PrevRefIPs        0
dtype: int64

In [8]:
traffic.shape

(1000000, 12)

 top and bottom 10 Websites with the highest numbers of visitors traffic

Assuming Higher Referring Subnets/IPs Indicate Higher Traffic

In [12]:

# Sort by RefSubNets 
top_traffic_domains = traffic.sort_values(by='RefSubNets', ascending=False).head(10)  # Top 10 domains
bottom_traffic_domains = traffic.sort_values(by='RefSubNets', ascending=False).tail(10)  # Bottom 10 domains (by highest RefSubNets)

In [10]:
top_traffic_domains

,GlobalRank,TldRank,Domain,TLD,RefSubNets,RefIPs,IDN_Domain,IDN_TLD,PrevGlobalRank,PrevTldRank,PrevRefSubNets,PrevRefIPs
0,1,1,google.com,com,471274,2151358,google.com,com,1,1,471248,2147402
1,2,2,facebook.com,com,465424,2250631,facebook.com,com,2,2,465297,2247135
2,3,3,youtube.com,com,420579,1852995,youtube.com,com,3,3,420483,1848940
3,4,4,twitter.com,com,404985,1757127,twitter.com,com,4,4,404998,1753939
4,5,5,instagram.com,com,364746,1598085,instagram.com,com,5,5,364618,1594892
5,6,6,linkedin.com,com,337391,1319082,linkedin.com,com,6,6,337393,1316218
6,7,7,apple.com,com,263655,804726,apple.com,com,7,7,263416,801213
7,8,8,microsoft.com,com,260546,739096,microsoft.com,com,8,8,260326,736093
8,9,9,googletagmanager.com,com,254115,863843,googletagmanager.com,com,9,9,254162,861615
9,10,1,wikipedia.org,org,246612,831384,wikipedia.org,org,10,1,246522,828772

In [11]:
bottom_traffic_domains

,GlobalRank,TldRank,Domain,TLD,RefSubNets,RefIPs,IDN_Domain,IDN_TLD,PrevGlobalRank,PrevTldRank,PrevRefSubNets,PrevRefIPs
999257,999258,484938,beninlotto.com,com,222,471,beninlotto.com,com,994132,482813,224,479
999258,999259,484939,jgpe-tea.com,com,222,471,jgpe-tea.com,com,988640,479994,225,475
999259,999260,30507,schluesseldienst-24-bochum.de,de,222,471,schluesseldienst-24-bochum.de,de,999696,30439,223,471
999260,999261,30508,schluesseldienst-swisttal-24.de,de,222,471,schluesseldienst-swisttal-24.de,de,994134,30249,224,477
999261,999262,484940,allpettoys.com,com,222,470,allpettoys.com,com,-1,-1,-1,-1
999262,999263,484941,danielderek.com,com,222,470,danielderek.com,com,-1,-1,-1,-1
999263,999264,484942,fiboomgas.com,com,222,470,fiboomgas.com,com,-1,-1,-1,-1
999264,999265,484943,safe-navi.com,com,222,470,safe-navi.com,com,988644,479998,225,475
999265,999266,30509,schluesseldienst-fuerth-24.de,de,222,470,schluesseldienst-fuerth-24.de,de,-1,-1,-1,-1
999999,1000000,485328,toyotamusicfactory.com,com,222,280,toyotamusicfactory.com,com,973201,471949,228,284

### Countries that have many articles written about them

first merge the news and rating dataset to a new one called combined_df

In [10]:

# Define a list of CSV filenames 
csv_files = [r"C:\Users\HP\Downloads\week00_data\data.csv", r"C:\Users\HP\Downloads\week00_data\rating.csv"]

# Read all CSV files into a list of DataFrames
all_dataframes = []
for filename in csv_files:
  df = pd.read_csv(filename)
  all_dataframes.append(df)

# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(all_dataframes, ignore_index=True)

# Now 'combined_df' contains the data from all CSV files
print(combined_df)

        article_id source_id                   source_name  \
0            89541       NaN  International Business Times
1            89542       NaN                    Prtimes.jp
2            89543       NaN                      VOA News
3            89545       NaN            The Indian Express
4            89547       NaN           The Times of Israel
...            ...       ...                           ...
163726      781108       NaN            The Indian Express
163727      781129       NaN                        Forbes
163728      781235       NaN                           NPR
163729      781240       NaN                        Forbes
163730      781308       NaN                        Forbes

                                                   author  \
0                                          Paavan MATHEMA
1                                                     NaN
2              webdesk@voanews.com (Agence France-Presse)
3                                               Editorial
4                                             Jacob Magid
...                                                   ...
163726                                                PTI
163727  Tom Sanderson, Senior Contributor, \n Tom Sand...
163728                                    Brigid McCarthy
163729  Gary Stern, Contributor, \n Gary Stern, Contri...
163730  Johan Hajji, Forbes Councils Member, \n Johan ...

                                                    title  \
0       UN Chief Urges World To 'Stop The Madness' Of ...
1                   RANDEBOOよりワンランク上の大人っぽさが漂うニットとベストが新登場。
2       UN Chief Urges World to 'Stop the Madness' of ...
3       Sikkim warning: Hydroelectricity push must be ...
4       200 foreigners, dual nationals cut down in Ham...
...                                                   ...
163726  Have done no wrong, only did party work, says ...
163727  FC Barcelona Guarantees $77.6 Million Champion...
163728  Three hospitals ignored her gravely ill fiancé...
163729  Kerber’s Farm: Bringing Farm To Table To Manha...
163730  Tips For Investing In Short-Term Rentals In Dubai

                                              description  \
0       UN Secretary-General Antonio Guterres urged th...
1       [株式会社Ainer]\nRANDEBOO（ランデブー）では2023年7月18日(火)より公...
2       UN Secretary-General Antonio Guterres urged th...
3       Ecologists caution against the adverse effects...
4       France lost 35 citizens, Thailand 33, US 31, U...
...                                                   ...
163726  The High Court today allowed Shivakumar to wit...
163727  FC Barcelona have guaranteed at least $77.6 mi...
163728  Forty years ago, Sarah Lubarsky came home from...
163729  A farmstand in Long Island, Kerber’s Farms has...
163730  By exploring your options and keeping a few be...

                                                      url  \
0       https://www.ibtimes.com/un-chief-urges-world-s...
1       https://prtimes.jp/main/html/rd/p/000000147.00...
2       https://www.voanews.com/a/un-chief-urges-world...
3       https://indianexpress.com/article/opinion/edit...
4       https://www.timesofisrael.com/200-foreigners-d...
...                                                   ...
163726  https://indianexpress.com/article/cities/banga...
163727  https://www.forbes.com/sites/tomsanderson/2023...
163728  https://www.npr.org/2023/11/29/1215016001/heal...
163729  https://www.forbes.com/sites/garystern/2023/11...
163730  https://www.forbes.com/sites/forbesbusinesscou...

                                             url_to_image  \
0       https://d.ibtimes.com/en/full/4496078/nepals-g...
1       https://prtimes.jp/i/32220/147/ogp/d32220-147-...
2       https://gdb.voanews.com/01000000-0a00-0242-60f...
3       https://images.indianexpress.com/2023/10/edit-...
4       https://static.timesofisrael.com/www/uploads/2...
...                                                   ...
163726  https://images.indianexpress.com/2023/11/DK-Sh...
163727  https://imageio.forbes.com/specials-images/ima...
163728  https://media.npr.org/assets/img/2023/11/23/sa...
163729  https://imageio.forbes.com/specials-images/ima...
163730  https://imageio.forbes.com/specials-images/ima...

                      published_at  \
0       2023-10-30 10:12:35.000000
1       2023-10-06 04:40:02.000000
2       2023-10-30 10:53:30.000000
3       2023-10-06 01:20:24.000000
4       2023-10-27 01:08:34.000000
...                            ...
163726         2023-11-29 10:57:22
163727         2023-11-29 08:41:18
163728         2023-11-29 10:01:12
163729         2023-11-29 13:44:33
163730         2023-11-29 14:00:00

                                                  content category  \
0       UN Secretary-General Antonio Guterres urged th...    Nepal
1       RANDEBOO2023718()WEB2023 Autumn Winter \n"Nepa...    Nepal
2       Kathmandu, Nepal  UN Secretary-General Antonio...    Nepal
3       At least 14 persons lost their lives and more ...    Nepal
4       Scores of foreign citizens were killed, taken ...    Nepal
...                                                   ...      ...
163726  Karnataka Deputy Chief Minister D K Shivakumar...     Home
163727  FC Barcelona have guaranteed at least $767.6 m...     Home
163728  The photo from David and Sarah Lubarsky's wedd...     Home
163729  Kerbers Farm: Bringing Farm To Table To Manhat...     Home
163730  Cofounder at UpperKey. Passionate about proper...     Home

                                             full_content  \
0       UN Secretary-General Antonio Guterres urged th...
1                                                     NaN
2                                                     NaN
3       At least 14 persons lost their lives and more ...
4                                                     NaN
...                                                   ...
163726                                                NaN
163727                                                NaN
163728                                                NaN
163729                                                NaN
163730                                                NaN

                                                  article title_sentiment
0                                                     NaN             NaN
1                                                     NaN             NaN
2                                                     NaN             NaN
3                                                     NaN             NaN
4                                                     NaN             NaN
...                                                   ...             ...
163726  Karnataka Deputy Chief Minister D K Shivakumar...         Neutral
163727  FC Barcelona have guaranteed at least $767.6 m...         Neutral
163728  The photo from David and Sarah Lubarsky's wedd...        Negative
163729  Kerber’s Farm: Bringing Farm To Table To Manha...         Neutral
163730  Cofounder at UpperKey. Passionate about proper...         Neutral

[163731 rows x 14 columns]

In [14]:
combined_df = pd.DataFrame(combined_df)
combined_df

,article_id,source_id,source_name,author,title,description,url,url_to_image,published_at,content,category,full_content,article,title_sentiment
0,89541,NaN,International Business Times,Paavan MATHEMA,UN Chief Urges World To 'Stop The Madness' Of ...,UN Secretary-General Antonio Guterres urged th...,https://www.ibtimes.com/un-chief-urges-world-s...,https://d.ibtimes.com/en/full/4496078/nepals-g...,2023-10-30 10:12:35.000000,UN Secretary-General Antonio Guterres urged th...,Nepal,UN Secretary-General Antonio Guterres urged th...,NaN,NaN
1,89542,NaN,Prtimes.jp,NaN,RANDEBOOよりワンランク上の大人っぽさが漂うニットとベストが新登場。,[株式会社Ainer]\nRANDEBOO（ランデブー）では2023年7月18日(火)より公...,https://prtimes.jp/main/html/rd/p/000000147.00...,https://prtimes.jp/i/32220/147/ogp/d32220-147-...,2023-10-06 04:40:02.000000,"RANDEBOO2023718()WEB2023 Autumn Winter \n""Nepa...",Nepal,NaN,NaN,NaN
2,89543,NaN,VOA News,webdesk@voanews.com (Agence France-Presse),UN Chief Urges World to 'Stop the Madness' of ...,UN Secretary-General Antonio Guterres urged th...,https://www.voanews.com/a/un-chief-urges-world...,https://gdb.voanews.com/01000000-0a00-0242-60f...,2023-10-30 10:53:30.000000,"Kathmandu, Nepal UN Secretary-General Antonio...",Nepal,NaN,NaN,NaN
3,89545,NaN,The Indian Express,Editorial,Sikkim warning: Hydroelectricity push must be ...,Ecologists caution against the adverse effects...,https://indianexpress.com/article/opinion/edit...,https://images.indianexpress.com/2023/10/edit-...,2023-10-06 01:20:24.000000,At least 14 persons lost their lives and more ...,Nepal,At least 14 persons lost their lives and more ...,NaN,NaN
4,89547,NaN,The Times of Israel,Jacob Magid,"200 foreigners, dual nationals cut down in Ham...","France lost 35 citizens, Thailand 33, US 31, U...",https://www.timesofisrael.com/200-foreigners-d...,https://static.timesofisrael.com/www/uploads/2...,2023-10-27 01:08:34.000000,"Scores of foreign citizens were killed, taken ...",Nepal,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163726,781108,NaN,The Indian Express,PTI,"Have done no wrong, only did party work, says ...",The High Court today allowed Shivakumar to wit...,https://indianexpress.com/article/cities/banga...,https://images.indianexpress.com/2023/11/DK-Sh...,2023-11-29 10:57:22,Karnataka Deputy Chief Minister D K Shivakumar...,Home,NaN,Karnataka Deputy Chief Minister D K Shivakumar...,Neutral
163727,781129,NaN,Forbes,"Tom Sanderson, Senior Contributor, \n Tom Sand...",FC Barcelona Guarantees $77.6 Million Champion...,FC Barcelona have guaranteed at least $77.6 mi...,https://www.forbes.com/sites/tomsanderson/2023...,https://imageio.forbes.com/specials-images/ima...,2023-11-29 08:41:18,FC Barcelona have guaranteed at least $767.6 m...,Home,NaN,FC Barcelona have guaranteed at least $767.6 m...,Neutral
163728,781235,NaN,NPR,Brigid McCarthy,Three hospitals ignored her gravely ill fiancé...,"Forty years ago, Sarah Lubarsky came home from...",https://www.npr.org/2023/11/29/1215016001/heal...,https://media.npr.org/assets/img/2023/11/23/sa...,2023-11-29 10:01:12,The photo from David and Sarah Lubarsky's wedd...,Home,NaN,The photo from David and Sarah Lubarsky's wedd...,Negative
163729,781240,NaN,Forbes,"Gary Stern, Contributor, \n Gary Stern, Contri...",Kerber’s Farm: Bringing Farm To Table To Manha...,"A farmstand in Long Island, Kerber’s Farms has...",https://www.forbes.com/sites/garystern/2023/11...,https://imageio.forbes.com/specials-images/ima...,2023-11-29 13:44:33,Kerbers Farm: Bringing Farm To Table To Manhat...,Home,NaN,Kerber’s Farm: Bringing Farm To Table To Manha...,Neutral
163730,781308,NaN,Forbes,"Johan Hajji, Forbes Councils Member, \n Johan ...",Tips For Investing In Short-Term Rentals In Dubai,By exploring your options and keeping a few be...,https://www.forbes.com/sites/forbesbusinesscou...,https://imageio.forbes.com/specials-images/ima...,2023-11-29 14:00:00,Cofounder at UpperKey. Passionate about proper...,Home,NaN,Cofounder at UpperKey. Passionate about proper...,Neutral

In [15]:
combined_df.isna().sum()

article_id              0
source_id          121465
source_name             0
author              10382
title                  40
description           393
url                     0
url_to_image         9075
published_at            0
content                 0
category               63
full_content       105299
article            105375
title_sentiment    105375
dtype: int64